language: python
python:
  - "3.6"
  - "nightly"
install: "pip install -r requirements-dev.txt"
script: py.test -v --cov=./
after_success:
  - codecov
deploy:
  provider: pypi
  user: "diogommartins"
  password:
    secure: "UOWVJ2sSOYyDC73lXYX83FjwDro3WCXAxdTsBxHmgdRN9yDxDG84Wj04xEiQ/3XWS+Pa/7FAXvb+FW7jyWvXDqS0EGNxKH/Z6EslJZFdIQC+Hs1LpHdqTlrtv3k9JdKODjuWNkrtQsTPr9/PscmHdDTikqolMhUGFLFCdTP75BDLN4pz2R58Q7DnJj1t46uUFJsSvaAbzVhd3u5vZ6AskGg4hf6pe/b8KxVWO6i1PTXOUGv70iOU4rJ3V4ZxMyj8OIgSYJAnqy+poq+L5GsJCOLfuLhYO48BxHetMlHDZz3QSNk6FAaHueLywmHz1Rk0RVeMGTCeqB+WLqH5WEFHJsT997mVh64ePRa3WTDKdQCj4RwgdloYlRlGiTltR4MovD/LXeX5apBHvEdjsJdOEeVR0OxUmdeYIxZV1JzYK+kDsDuEOaQgWfj0Die31T+p4aSgDCAI3o1sui+O5JUxvCOX4ZqJO+aunHHzjwyBKxK5pAl0VAwyT0Y723qyTPbTArI+dA/s0Q9Vvv2eom86FvnAhXuoJ7Ng/WjSjXhUnMCRVpSzQh5+JQkiZhTFCDw8gTX3Sgw8nIjK2NjWAW7NuZUn1eKS6L7JTzZeADfPjGVJ7IAj0eKZqDBWJ5qgzbjdyduWO8IE+go9UA4w4EnWVqKl01cf6Iy7nN/0nwlW1LY="
  on:
    tags: true
